### ISSUE TITLE
Automatic import configuration for the Aurelia-CLI

### ISSUE THREAD

**Issue by zewa666** [aurelia-toolbelt/aurelia-toolbelt#50]
Hi there, nice work you guys started here.
In order to make the getting started easier for Aurelia-CLI users, based on RequireJS and SystemJS, it would be helpful if your package.json could include the instructions for having dependencies automatically added. You can take a look here for [an example](https://github.com/zewa666/aurelia-store/blob/master/package.json#L119)

**Comment by HamedFathi** [comment]
@zewa666 

Great idea, we don't know about that, so we will do that soon

**Comment by shahabganji** [comment]
Dear @zewa666, 

Is it possible to have such a feature for webpack too?

**Comment by zewa666** [comment]
Well If your Plugin states dependencies in its package.json webpack should be able to do that out of the box.

**Comment by zewa666** [comment]
I'm not really familiar with webpack but it sounds like there is no real way around having a dedicated config loader adaption. Might try to ping some people over at webpacks gitter repo.

**Comment by shahabganji** [comment]
I do not know how to bundle some javascript libraries to work with Aurelia CLI, requireJS or systemJS.
To name a few, jquery block UI, fuse.js, and  tokenize2. I would be  grateful if anyone could help

**Comment by khuongduybui** [comment]
now that `au import` is being deprecated, let's close this in favor of supporting the new bundler #76

**Comment by shahabganji** [comment]
closed in favor of [this](https://github.com/aurelia-toolbelt/aurelia-toolbelt/issues/76)
