### ISSUE TITLE
au bundle

### ISSUE THREAD

**Issue by johntom** [aurelia-toolbelt/aurelia-toolbelt#54]
Hi,
How do I  bundle aurelia-toolbelt with au-cli using au build --env prod? 
I followed the same pattern as aurlia-dialog modifying aurelia.json file in aurelia_project but get error when I try to use it 
 
 {
        "name": "aurelia-toolbelt.js",
        "dependencies": [
          {
              "name": "aurelia-toolbelt",
            "main": "index",
            "path": "../node_modules/aurelia-toolbelt/dist/commonjs",
            "resources": []
          },
          "jquery"
        ]
      },
Thanks,
John

**Comment by HamedFathi** [comment]
@johntom 

Hi,
Did you ever try our starter kits?

[aut-webpack-starter-kit](https://github.com/aurelia-toolbelt/aut-webpack-starter-kit)
[aut-requirejs-starter-kit](https://github.com/aurelia-toolbelt/aut-requirejs-starter-kit)

both of them are based on `Aurelia-CLI`

I executed `au build --env prod` on `aut-webpack-starter-kit` see the following picture

![2018-03-06_20-22-30](https://user-images.githubusercontent.com/8418700/37046105-c2e157cc-217c-11e8-9421-3d2c85221a9e.png)

As you see, we have no error

**Comment by johntom** [comment]
No, I will give it a go and get back to you. I need the bundle for my projects using http://www.frontendcreator.com. I currently use aurelia-bootstrap for the typeahead component but some issues with other stuff.
Thanks for prompt reply,
John

**Comment by johntom** [comment]
Hi,
I never used webpack before and while I'm getting amost identical results with node 8.9.4 and app shows in local browser, I need to  create a seperate bundle for aurelia-toolbelt to use with FEC (www,frontendcreator.com) How can I accoomplish that?
John

**Comment by shahabganji** [comment]
Hi @johntom,

> I need to create a seperate bundle for aurelia-toolbelt 
> How can I accomplish that?


That can be achieved by adding the following line to ```webpack.config.js``` file in [aut-webpack-starter-kit](https://github.com/aurelia-toolbelt/aut-webpack-starter-kit)

```
...
,
  entry: {
    app: ['aurelia-bootstrapper'],
    'aurelia-toolbelt': ['aurelia-toolbelt']
  },
...
```

Shahab

**Comment by shahabganji** [comment]
@johntom any success?

**Comment by shahabganji** [comment]
I close the issue because of inactivity
