### ISSUE TITLE
Button Groups does not have any value or model to bind to

### ISSUE THREAD

**Issue by ghiscoding** [aurelia-toolbelt/aurelia-toolbelt#57]
This is a continuation of a post made in another issue (which is now closed).

>Thanks for your nice explanation, I actually realized why I thought it wasn't working. It actually does work but the button of modal demo was actually simply shown as just text (not the look of a button, however the text was clickable), so the modal demo also needs the `aurelia-toolbelt/components/bootstrap/button` for it to show the same as the demo. 

>I don't want to make this simple issue become a long post of multiple subjects but I have another  question. I would like to use the Button Groups as radio button, to make the user choose 1 option out of 3 options, however in your demo I don't see how to bind the `checked` value. I also cannot visually see which option is clicked, I'm not sure if that is a Bootstrap issue though

Your reply was

> This feature of bootstrap is not implemented in toolbelt 🙈, because at the time of writing I had no idea whether it should be a mixed feature of abt-button or abt-button-group or another separate component. I would grateful if you could come up with a suggestion and will be more than happy to implement your proposal. if interested please open a new issue to track this feature.

**Comment by ghiscoding** [comment]
To answer your question, I would go with something similar to what was implemented in [Aurelia-Bootstrap](https://tochoromero.github.io/aurelia-bootstrap/#/buttons). I could use his lib, but there's no update since a year and so I don't think they support Bootstrap 4 very well.

**Comment by shahabganji** [comment]
> Also if that helps in anything, I also have an open source library for Aurelia-Bootstrap-Select which 

There is a [dropdown component](https://aurelia-toolbelt.github.io/#/bootstrap/dropdown) available in the toolbelt, albeit your select has more features than the bootstrap itself, BTW, I didn't get your point about [Aurelia-Bootstrap-Select](https://ghiscoding.github.io/Aurelia-Bootstrap-Plugins/#/bootstrap-plugins/bootstrap-select). 

> Here's the code for the other lib that I reference, here's the Button as Radio and also a separate file for Button as Checkbox

As far as I understand they are custom attributes and not components, however, I'll deep dive into the codes you mentioned and try to add your required(missed) feature into the toolbelt.

**Comment by ghiscoding** [comment]
@shahabganji 
The Aurelia-Bootstrap-Select example was to show that I've implemented both the `value.bind` (which in the example below returns the id) and the `model.bind` (which below has the complete object selected). The reason I like this approach is that sometime I just want the id (or the string) and other times I want the entire object since I might use other properties of the object. 

On the sample page of [Aurelia-Bootstrap-Select](https://ghiscoding.github.io/Aurelia-Bootstrap-Plugins/#/bootstrap-plugins/bootstrap-select), I show both the `value` and `model` (item), see them below where the red arrows are pointing to.

![bootstrap-select](https://user-images.githubusercontent.com/643976/45000587-2bd1f200-af94-11e8-8384-f9c311946e33.png)

**Comment by shahabganji** [comment]
@ghiscoding 

Thanks for your guidance, actually we have such implementations for [toggle](https://aurelia-toolbelt.github.io/#/bootstrap/toggle) and undocumented controls like [checkboxes](https://aurelia-toolbelt.github.io/#/vanilla/checkbox) & [radio buttons](https://aurelia-toolbelt.github.io/#/vanilla/radio) , the source code is [here](https://github.com/aurelia-toolbelt/aurelia-toolbelt/tree/master/src/components/vanilla/pretty), might be useful for your project too.

if you are intereseted we have a bunch of undocumented components [here](https://github.com/aurelia-toolbelt/aurelia-toolbelt/tree/master/src/components/vanilla), worth looking at, should you require any further information or suggestions about those controls please do not hesitate to contact me.

**Comment by ghiscoding** [comment]
@shahabganji 
Sweet, this looks exactly what I wanted to have. I'll give it a try later tonight.  Thanks a lot

**Comment by shahabganji** [comment]
@ghiscoding 

Your welcome comrade. so I close the issue and will publish an npm package as soon as you confirm. if you find any problem do not hesitate to reopen the issue.

**Comment by ghiscoding** [comment]
@shahabganji 
As promised, I took a bigger look at the documentation that you provided and everything looks good, I see you added even more than I expected. All the binding that you added make this Radio Button component as something that I can't wait to use. I'll patiently wait for your new release and in the mean time, I'll up vote ⭐️  

Thanks for the amazing support

**Comment by shahabganji** [comment]
@ghiscoding 

I published [v1.0.0 npm package](https://www.npmjs.com/package/aurelia-toolbelt). It is worth knowing that there is a nuget package for .NET developers [here](https://www.nuget.org/packages/AureliaToolbelt.AspNetCore/1.0.0), if your are nice to know about.
