### ISSUE TITLE
Doesn't work with Webpack 4

### ISSUE THREAD

**Issue by graycrow** [aurelia-toolbelt/aurelia-toolbelt#61]
I downloaded the [aut-webpack4-starter-kit](https://github.com/aurelia-toolbelt/aut-webpack4-starter-kit) and upgraded aurelia-toolbelt to version 1.1.1. As a result, now application throws few errors.

1. `Uncaught TypeError: Cannot read property 'get' of undefined` at https://github.com/aurelia-toolbelt/aurelia-toolbelt/blob/3df963a60fea743fc1f47882e7fe6610a70cf75a/src/decorators/inject-css.ts#L13

2. `Unhandled rejection Error: Unable to find module with ID: aurelia-toolbelt/external-resources/css/toastr.css`

If I limit the plugin registration to specific component (like `.plugin(PLATFORM.moduleName("aurelia-toolbelt/components/bootstrap/dropdown"))`), then it starts to complain about missing html files, for example `Unhandled rejection Error: Unable to find module with ID: aurelia-toolbelt/components/bootstrap/dropdown/abt-dropdown.html`

**Comment by graycrow** [comment]
Ok, with AureliaToolbelt.AspNetCore version 1.0.1-beta and .NET Core  2.1 issue 1 is gone but issue 2 still exists: `Unhandled rejection Error: Unable to find module with ID: aurelia-toolbelt/external-resources/css/toastr.css`

**Comment by shahabganji** [comment]
May I ask you to use [version 1](https://www.nuget.org/packages/AureliaToolbelt.AspNetCore/1.0.0) ? 
Sorry I’m on mobile and cannot check them.

**Comment by graycrow** [comment]
Tested with 1.0.0, the results are the same as with 1.0.1-beta.

**Comment by shahabganji** [comment]
@graycrow 

Thanks for your support, anyway, the problem you mentioned is a known issue 🙈 😄 for our library and its due totally to [this line](https://github.com/aurelia-toolbelt/aurelia-toolbelt/blob/master/src/services/jquery/toastr/toastr-service.ts#L13). As @ghiscoding said, it pertains to how CSS loaders work, that's not a blocking issue though, and the library works seamlessly 🤞 . I should remove the above-mentioned line  and release a new package. Hence, I need more time to create some repositories from scratch with the @ghiscoding 's suggestions.

**Comment by shahabganji** [comment]
@graycrow, @ghiscoding  

Hi, I have updated aurelia-toolbelt to v1.2.1 and respectively the [dotnet template](https://www.nuget.org/packages/AureliaToolbelt.AspNetCore/1.2.1) ( ```dotnet new --install AureliaToolbelt.AspNetCore::1.2.1``` ) and [webpack starter kit](https://github.com/aurelia-toolbelt/aut-webpack4-starter-kit), I checked them and they look errorless. Can you guys do me a favor and make a double check?

**Comment by ghiscoding** [comment]
I probably won't have time to try this out until next weekend. But so far I can say that from the entire set of component, I am not able to make the `aurelia-dialog` working, so the recent changes in your Modal demo doesn't work for me. However this is probably not in your .Net demo.

**Comment by ghiscoding** [comment]
@shahabganji 
I tried the `webpack starter kit` and I'm getting an error. However I'm not sure how to star the project. Is it just `npm start`? If so, this is what I'm getting

```bash
C:\aut-webpack4-starter-kit\node_modules\webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\aut-webpack4-starter-kit\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at Object.<anonymous> (C:\aut-webpack4-starter-kit\node_modules\webpack-dev-server\bin\webpack-dev-server.js:84:40)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
The script called "webpack.server" which runs "webpack-dev-server -d --devtool '#source-map' --inline --env.server" failed with
exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.3/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "webpack" which runs "nps webpack.server" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.3/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "default" which runs "nps webpack" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.3/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aut-starter-kit-webpack@0.1.0 start: `nps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aut-starter-kit-webpack@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I didn't try the other repo since I don't think that I have .Net Core installed anymore

**Comment by shahabganji** [comment]
@ghiscoding 

I always use ```au run --watch```, however in your case I tried ```npm start``` and that worked too, I got no error. have you tried ```yarn install``` before running the project?

![npm](https://user-images.githubusercontent.com/4405518/46567579-ff6a1680-c941-11e8-9a40-443440394e8c.jpg)

![npm2](https://user-images.githubusercontent.com/4405518/46567610-7ef7e580-c942-11e8-86bb-6bfd0fd4c074.jpg)


![npm3](https://user-images.githubusercontent.com/4405518/46567613-8a4b1100-c942-11e8-8e1a-bae20a17a4b6.png)

**Comment by ghiscoding** [comment]
I tried a few things and still can't run it. I just got recent `aurelia-cli` version `0.35.1` too. I have `Gulp` and `aurelia-cli` installed globally but that is all. Also I'm on Windows, so I'm not sure if that is the problem. Anyhow, I won't spend more time on this. The best would be to hear about @graycrow and see if it works for him.

**Comment by shahabganji** [comment]
@ghiscoding 

Thanks for your patience and support, let's keep our fingers crossed :crossed_fingers:
